name: Magno Valdetaro
description: Apenas um jovem rapaz brincando de codificar.

include: ['.htaccess']

#Links
permalink: /blog/:title
url:       http://mvaldetaro.github.io

# Encode
encoding: UTF-8

# GitHub Defaults
lsi: false
pygments: true
safe: true

# UTF-8 & parse errors fix
markdown: redcarpet

#ignore
exclude: ['Thumbs.db', 'node_modules', 'package.json']